name: hello world workflow
on:
  push:
jobs:
   hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: |
             echo "This is the final step of the workflow."
             date
             ls -la
             pwd
   deploy_job:
    runs-on: ubuntu-latest
    needs: hello_world_job
    steps:
      - name: Deploy Step
        run: echo "Deploying the application..."
      - name: Display environment variables
        run: printenv
      - name: Show disk space usage
        run: df -h     
   hello_world_job_2:
    runs-on: ubuntu-latest
    needs: [hello_world_job,deploy_job]
    steps:
      - name: Hello World Step 2
        run: echo "Hello from the second job!"
      - name: Display system information
        run: uname -a
      - name: Check disk usage
        run: df -h     